name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Install and Build
      run: |
        yarn &&
        yarn vuepress build docs
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@3.5.9
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      with: 
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: deploy
        FOLDER: docs/.vuepress/dist